language: smalltalk

# Select operating system(s)
os:
  - linux
  
# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo32-6.1  
  - Pharo64-6.1
  - Pharo32-7.0  
  - Pharo64-7.0
  - Pharo64-8.0
